linters:
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - gci
    - gofmt
    - gomnd
    - gocognit

run:
  timeout: 5m

linters-settings:
  gocognit:
    min-complexity: 10
