name: CI

on:
  push:
    branches:
      - "main"
  pull_request:

env:
  GO_VERSION: 1.21.4

jobs:
  check-mod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true
      - run: go mod tidy && git diff --exit-code go.sum

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - uses: golangci/golangci-lint-action@v6

  test:
    permissions:
      checks: write
      pull-requests: write
      actions: read
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: go test -v -race -coverprofile=coverage.out ./...

      - name: Report coverage
        uses: k1LoW/octocov-action@v1
